config/routes.rb
Rails.application.routes.draw do

  resources :enrollment_session_logs
  resources :enrollments
  get 'cohorts/(:cohort_id)/roster', to: 'enrollments#roster', as: 'master_roster'
  
  get 'entry_surveys/recode', to: 'entry_surveys#recode', as: 'recode_entry_surveys'
  get 'exit_surveys/recode', to: 'exit_surveys#recode', as: 'recode_exit_surveys'
  get 'entry_surveys/recode/(:id)', to: 'entry_surveys#recode_one', as: 'recode_entry_survey'
  get 'exit_surveys/recode/(:id)', to: 'exit_surveys#recode_one', as: 'recode_exit_survey'
  resources :exit_surveys
  resources :entry_surveys
  get 'providers/(:id)/surveys', to: 'providers#survey_results', as: 'provider_surveys'
  
  resources :incentives
  resources :staff_training_surveys, except: [ :new ]
  resources :staff_training_events
  get 'new_staff_survey/(:lookup)', to: 'staff_training_surveys#new', as: 'new_staff_training_survey'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }

  resources :coho_downs do
    member do
      delete :delete_receipt
    end
  end

  resources :handouts do
    member do
      delete :delete_document
    end
  end
  
  resources :coho_down_attends
  
  resources :session_logs do
    member do
      delete :delete_receipt
    end
  end
  resources :coho_ups
  resources :cohorts
  resources :module_lookups
  resources :providers
  resources :grantees
  resources :session_modules
  get '/filters', to: 'filters#index', as: 'filters'
  post 'filters/:provider_id', to: 'filters#add', as: 'add_filter'
  delete 'filters/:id', to: 'filters#remove', as: 'remove_filter'
  
  get '/finalize_annual_data', to: 'providers#finalize', as: 'finalize_provider'

  get '/incentivize/:species/:variety/:fingerprint', to: 'incentives#record_fingerprint', as: 'incentive_fingerprint'

  get 'users/', to: 'users#index'

  post 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post 'users/:id/activate', to: 'users#activate', as: 'activate_user'

  post 'users/:id/decoordinate', to: 'users#decoordinate', as: 'decoordinate_user'
  post 'users/:id/coordinate', to: 'users#coordinate', as: 'coordinate_user'

  post 'users/:id/devicar', to: 'users#devicar', as: 'devicar_user'
  post 'users/:id/vicar', to: 'users#vicar', as: 'vicar_user'
  
  post 'users/:id/su_off', to: 'users#detechnician', as: 'detechnician_user'
  post 'users/:id/su_on', to: 'users#technician', as: 'technician_user'
  
  post 'users/:id/detestify', to: 'users#detestify', as: 'detestify_user'
  post 'users/:id/testify', to: 'users#testify', as: 'testify_user'

  post 'users/add_admin', to: 'users#add_site_admin_role', as: 'add_site_admin_for_user'
  post 'users/:id/del_admin/:pid', to: 'users#del_site_admin_role', as: 'del_site_admin_for_user'

  post 'users/add_facilitator', to: 'users#add_facilitator_role', as: 'add_facilitator_for_user'
  post 'users/:id/del_facilitator/:pid', to: 'users#del_facilitator_role', as: 'del_facilitator_for_user'

  get 'cohorts/:id/facilitate', to: 'cohorts#facilitate', as: 'facilitate'
  get 'cohorts/:id/survey', to: 'cohorts#survey', as: 'survey'
  get 'cohorts/:id/enroll', to: 'cohorts#enroll', as: 'enroll'

  post 'handouts/:id/deactivate', to: 'handouts#deactivate', as: 'deactivate_handout'
  post 'handouts/:id/activate', to: 'handouts#activate', as: 'activate_handout'

  post 'enrollments/:id/hide', to: 'enrollments#hide', as: 'hide_enrollment'
  
  get 'reports/registration', to: 'reports#user_registrations', as: 'registration_report'
  get 'reports/activity', to: 'reports#recent_changes', as: 'activity_report'
  get 'reports/at-a-glance', to: 'reports#visualize_cohorts', as: 'visualize_cohorts'
  get 'reports/daily-reach', to: 'reports#daily_reach', as: 'daily_reach'
  get 'reports/outcomes/activities', to: 'reports#outcomes_dashboard_activities', as: 'outcomes_dashboard_activities'
  get 'reports/outcomes/outcomes', to: 'reports#outcomes_dashboard_outcomes', as: 'outcomes_dashboard_outcomes'
  get 'reports/outcomes/demographics', to: 'reports#outcomes_dashboard_demographics', as: 'outcomes_dashboard_demographics'
  get 'reports/outcomes/aggregated', to: 'reports#outcomes_dashboard_aggregated', as: 'outcomes_dashboard_aggregated'
  

  
  get 'reports/cir', to: 'reports#mpr_helper', as: 'mpr_helper'
  get 'reports/ppr', to: 'reports#ppr', as: 'ppr'
  #get 'reports/pmms/ard/:pid/:cname', to: 'reports#pmms_ard_program', as: 'pmms_ard_program'
  #get 'reports/pmms/ard/', to: 'reports#pmms_ard_program_index', as: 'pmms_ard_program_index'
  get 'reports/pmms/surveys/:provider_id/:curriculum_initials', to: 'reports#pmms_surveys', as: 'participant_surveys'
  get 'reports/pmms/surveys', to: 'reports#pmms_survey_index', as: 'pmms_survey_index'
  
  get 'reports/ppr/csv/cbo', to: 'reports#ppr_csv_cbo', as: 'get_ppr_csv_cbo'
  get 'reports/ppr/csv/ahyd', to: 'reports#ppr_csv_ahyd', as: 'get_ppr_csv_ahyd'
  

  root 'pages#index'
end

app/models/staff_training_event.rb
class StaffTrainingEvent < ApplicationRecord
  has_many :staff_training_surveys
end

app/controllers/staff_training_events_controller.rb
class StaffTrainingEventsController < ApplicationController
  before_action :set_staff_training_event, only: %i[ show edit update destroy ]

  # GET /staff_training_events or /staff_training_events.json
  def index
    authorize StaffTrainingEvent, :retrieve?
    @staff_training_events = policy_scope(StaffTrainingEvent)
  end

  # GET /staff_training_events/1 or /staff_training_events/1.json
  def show
    authorize StaffTrainingEvent, :retrieve?
  end

  # GET /staff_training_events/new
  def new
    authorize StaffTrainingEvent, :create?
    @staff_training_event = StaffTrainingEvent.new
    @staff_training_event[:period] = Prep::Constants::Year
  end

  # GET /staff_training_events/1/edit
  def edit
    authorize StaffTrainingEvent, :update?
  end

  # POST /staff_training_events or /staff_training_events.json
  def create
    authorize StaffTrainingEvent, :create?
    
    
    #@staff_training_event = StaffTrainingEvent.new(staff_training_event_params)
    
    strong_staff_training_event_params = staff_training_event_params
    strong_staff_training_event_params[:lookup] = SecureRandom.uuid
    
    @staff_training_event = StaffTrainingEvent.new(strong_staff_training_event_params)

    respond_to do |format|
      if @staff_training_event.save
        format.html { redirect_to @staff_training_event, notice: "Staff training event was successfully created." }
        format.json { render :show, status: :created, location: @staff_training_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff_training_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_training_events/1 or /staff_training_events/1.json
  def update
    authorize StaffTrainingEvent, :update?
    respond_to do |format|
      if @staff_training_event.update(staff_training_event_params)
        format.html { redirect_to @staff_training_event, notice: "Staff training event was successfully updated." }
        format.json { render :show, status: :ok, location: @staff_training_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff_training_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_training_events/1 or /staff_training_events/1.json
  def destroy
    authorize StaffTrainingEvent, :destroy?
    @staff_training_event.destroy
    respond_to do |format|
      format.html { redirect_to staff_training_events_url, notice: "Staff training event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_training_event
      @staff_training_event = StaffTrainingEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_training_event_params
      params.require(:staff_training_event).permit(:training_name, :training_date, :training_place, :training_trainer, :period, :lookup)
    end
end

app/helpers/staff_training_events_helper.rb
module StaffTrainingEventsHelper
end

app/views/staff_training_events/_form.html.erb
<%= form_with(model: staff_training_event) do |form| %>
  <% if staff_training_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff_training_event.errors.count, "error") %> prohibited this staff_training_event from being saved:</h2>

      <ul>
        <% staff_training_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :training_name %>
    <%= form.text_field :training_name %>
  </div>

  <div class="field">
    <%= form.label :training_date %>
    <%= form.date_select :training_date %>
  </div>

  <div class="field">
    <%= form.label :training_place %>
    <%= form.text_field :training_place %>
  </div>

  <div class="field">
    <%= form.label :training_trainer %>
    <%= form.text_field :training_trainer %>
  </div>

  <div class="field">
    <%= form.label :period %>
    <%= form.number_field :period %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staff_training_events/edit.html.erb
<h1>Editing Staff Training Event</h1>

<%= render 'form', staff_training_event: @staff_training_event %>

<%= link_to 'Show', @staff_training_event %> |
<%= link_to 'Back', staff_training_events_path %>

app/views/staff_training_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staff Training Events</h1>

<table class="apa">
  <thead>
    <tr>
      <th>Training name</th>
      <th>Training date</th>
      <th>Responses</th>
      <th>Link to Take</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_training_events.each do |staff_training_event| %>
      <tr>
        <td><%= staff_training_event.training_name %></td>
        <td><%= staff_training_event.training_date %></td>
        <td><%= staff_training_event.staff_training_surveys.length %></td>
        <td><%= link_to 'Take Survey', new_staff_training_survey_path(lookup: staff_training_event.lookup) %></td>
        <td><%= link_to 'Show', staff_training_event %></td>
        <td><%= link_to 'Edit', edit_staff_training_event_path(staff_training_event) %></td>
        <td><%= link_to 'Destroy', staff_training_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff Training Event', new_staff_training_event_path %>

app/views/staff_training_events/new.html.erb
<h1>New Staff Training Event</h1>

<%= render 'form', staff_training_event: @staff_training_event %>

<%= link_to 'Back', staff_training_events_path %>

app/views/staff_training_events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @staff_training_event.training_name %></h1>
<p>
  <%= @staff_training_event.training_trainer %><br />
  <%= @staff_training_event.training_date.strftime("%B %-d, %Y") %><br />
  <%= @staff_training_event.training_place %><br />
</p>
<% if signed_in? %>
  <% if current_user.has_role?(:technician) %>
    <p>
      <strong>Period:</strong> <%= @staff_training_event.period %><br />
      <strong>Lookup:</strong> <%= @staff_training_event.lookup %>
    </p>
  <% end %>
<% end %>

<p>There are <%= @staff_training_event.staff_training_surveys.length %> surveys recorded for this event.</p>

<% if @staff_training_event.staff_training_surveys.length > 3 %>
  <table class="apa">
  <caption>Staff Training Survey Responses</caption>
    <tr>
      <th>Domain</th>
      <th colspan="5">
        <div class="row" style="border-bottom: 1px solid black; width: 100%; margin: auto"><div style="margin: auto">Totals</div></div>
        <div class="row; width: 100%">
          <div class="row">
            <div class="col-sm">(Strongly)</div>
            <div class="col-sm">Disagree</div>
            <div class="col-sm">Neutral</div>
            <div class="col-sm">Agree</div>
            <div class="col-sm">(Strongly)</div>
          </div>
        </div>
      </th>
    </tr>
    <tr>
      <td>Interest</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_interest: 1).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_interest: 2).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_interest: 3).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_interest: 4).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_interest: 5).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
    </tr>
    <tr>
      <td>Relevance</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_relevance: 1).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_relevance: 2).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_relevance: 3).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_relevance: 4).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_relevance: 5).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
    </tr>
    <tr>
      <td>Usability</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_use: 1).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_use: 2).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_use: 3).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_use: 4).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_use: 5).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
    </tr>
    <tr>
      <td>Sharable</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_share: 1).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_share: 2).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_share: 3).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_share: 4).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_share: 5).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
    </tr>
    <tr>
      <td>Will Recommend</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_recommend: 1).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_recommend: 2).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_recommend: 3).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_recommend: 4).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
      <td><%= ((@staff_training_event.staff_training_surveys.where(quality_will_recommend: 5).length * 100.to_f) / @staff_training_event.staff_training_surveys.length).to_i %>%</td>
    </tr>
  </table>
  
  <h2>What was good about the training?</h2>
  <% if @staff_training_event.staff_training_surveys.where("details_good <> ''").length > 0 %>
    <ul>
      <% @staff_training_event.staff_training_surveys.where("details_good <> ''").pluck(:details_good).map{|i| i.downcase}.uniq.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  <% else %>
    <p>(No responses)</p>
  <% end %>
  
  <h2>What could be better about the training?</h2>
  <% if @staff_training_event.staff_training_surveys.where("details_improvement <> ''").length > 0 %>
    <ul>
      <% @staff_training_event.staff_training_surveys.where("details_improvement <> ''").pluck(:details_improvement).map{|i| i.downcase}.uniq.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  <% else %>
    <p>(No responses)</p>
  <% end %>
  
<% else %>
  <p>There are not enough responses for reporting further information.</p>
<% end %>

<%= link_to 'Edit', edit_staff_training_event_path(@staff_training_event) %> |
<%= link_to 'Back', staff_training_events_path %>