config/routes.rb
Rails.application.routes.draw do

  resources :enrollment_session_logs
  resources :enrollments
  get 'cohorts/(:cohort_id)/roster', to: 'enrollments#roster', as: 'master_roster'
  
  get 'entry_surveys/recode', to: 'entry_surveys#recode', as: 'recode_entry_surveys'
  get 'exit_surveys/recode', to: 'exit_surveys#recode', as: 'recode_exit_surveys'
  get 'entry_surveys/recode/(:id)', to: 'entry_surveys#recode_one', as: 'recode_entry_survey'
  get 'exit_surveys/recode/(:id)', to: 'exit_surveys#recode_one', as: 'recode_exit_survey'
  resources :exit_surveys
  resources :entry_surveys
  get 'providers/(:id)/surveys', to: 'providers#survey_results', as: 'provider_surveys'
  
  resources :incentives
  resources :staff_training_surveys, except: [ :new ]
  resources :staff_training_events
  get 'new_staff_survey/(:lookup)', to: 'staff_training_surveys#new', as: 'new_staff_training_survey'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }

  resources :coho_downs do
    member do
      delete :delete_receipt
    end
  end

  resources :handouts do
    member do
      delete :delete_document
    end
  end
  
  resources :coho_down_attends
  
  resources :session_logs do
    member do
      delete :delete_receipt
    end
  end
  resources :coho_ups
  resources :cohorts
  resources :module_lookups
  resources :providers
  resources :grantees
  resources :session_modules
  get '/filters', to: 'filters#index', as: 'filters'
  post 'filters/:provider_id', to: 'filters#add', as: 'add_filter'
  delete 'filters/:id', to: 'filters#remove', as: 'remove_filter'
  
  get '/finalize_annual_data', to: 'providers#finalize', as: 'finalize_provider'

  get '/incentivize/:species/:variety/:fingerprint', to: 'incentives#record_fingerprint', as: 'incentive_fingerprint'

  get 'users/', to: 'users#index'

  post 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post 'users/:id/activate', to: 'users#activate', as: 'activate_user'

  post 'users/:id/decoordinate', to: 'users#decoordinate', as: 'decoordinate_user'
  post 'users/:id/coordinate', to: 'users#coordinate', as: 'coordinate_user'

  post 'users/:id/devicar', to: 'users#devicar', as: 'devicar_user'
  post 'users/:id/vicar', to: 'users#vicar', as: 'vicar_user'
  
  post 'users/:id/su_off', to: 'users#detechnician', as: 'detechnician_user'
  post 'users/:id/su_on', to: 'users#technician', as: 'technician_user'
  
  post 'users/:id/detestify', to: 'users#detestify', as: 'detestify_user'
  post 'users/:id/testify', to: 'users#testify', as: 'testify_user'

  post 'users/add_admin', to: 'users#add_site_admin_role', as: 'add_site_admin_for_user'
  post 'users/:id/del_admin/:pid', to: 'users#del_site_admin_role', as: 'del_site_admin_for_user'

  post 'users/add_facilitator', to: 'users#add_facilitator_role', as: 'add_facilitator_for_user'
  post 'users/:id/del_facilitator/:pid', to: 'users#del_facilitator_role', as: 'del_facilitator_for_user'

  get 'cohorts/:id/facilitate', to: 'cohorts#facilitate', as: 'facilitate'
  get 'cohorts/:id/survey', to: 'cohorts#survey', as: 'survey'
  get 'cohorts/:id/enroll', to: 'cohorts#enroll', as: 'enroll'

  post 'handouts/:id/deactivate', to: 'handouts#deactivate', as: 'deactivate_handout'
  post 'handouts/:id/activate', to: 'handouts#activate', as: 'activate_handout'

  post 'enrollments/:id/hide', to: 'enrollments#hide', as: 'hide_enrollment'
  
  get 'reports/registration', to: 'reports#user_registrations', as: 'registration_report'
  get 'reports/activity', to: 'reports#recent_changes', as: 'activity_report'
  get 'reports/at-a-glance', to: 'reports#visualize_cohorts', as: 'visualize_cohorts'
  get 'reports/daily-reach', to: 'reports#daily_reach', as: 'daily_reach'
  get 'reports/outcomes/activities', to: 'reports#outcomes_dashboard_activities', as: 'outcomes_dashboard_activities'
  get 'reports/outcomes/outcomes', to: 'reports#outcomes_dashboard_outcomes', as: 'outcomes_dashboard_outcomes'
  get 'reports/outcomes/demographics', to: 'reports#outcomes_dashboard_demographics', as: 'outcomes_dashboard_demographics'
  get 'reports/outcomes/aggregated', to: 'reports#outcomes_dashboard_aggregated', as: 'outcomes_dashboard_aggregated'
  

  
  get 'reports/cir', to: 'reports#mpr_helper', as: 'mpr_helper'
  get 'reports/ppr', to: 'reports#ppr', as: 'ppr'
  #get 'reports/pmms/ard/:pid/:cname', to: 'reports#pmms_ard_program', as: 'pmms_ard_program'
  #get 'reports/pmms/ard/', to: 'reports#pmms_ard_program_index', as: 'pmms_ard_program_index'
  get 'reports/pmms/surveys/:provider_id/:curriculum_initials', to: 'reports#pmms_surveys', as: 'participant_surveys'
  get 'reports/pmms/surveys', to: 'reports#pmms_survey_index', as: 'pmms_survey_index'
  
  get 'reports/ppr/csv/cbo', to: 'reports#ppr_csv_cbo', as: 'get_ppr_csv_cbo'
  get 'reports/ppr/csv/ahyd', to: 'reports#ppr_csv_ahyd', as: 'get_ppr_csv_ahyd'
  

  root 'pages#index'
end

app/models/handout.rb
class Handout < ApplicationRecord
  has_one_attached :document
end

app/controllers/handouts_controller.rb
class HandoutsController < ApplicationController
  before_action :set_handout, only: %i[ show edit update destroy activate deactivate ]

  # GET /handouts or /handouts.json
  def index
    authorize Handout, :retrieve?
    @handouts = policy_scope(Handout)
  end

  # GET /handouts/1 or /handouts/1.json
  def show
    authorize Handout, :retrieve?
  end

  # GET /handouts/new
  def new
    authorize Handout, :create?
    @handout = Handout.new
  end

  # GET /handouts/1/edit
  def edit
    authorize Handout, :update?
  end

  # POST /handouts or /handouts.json
  def create
    authorize Handout, :create?
    @handout = Handout.new(handout_params)

    respond_to do |format|
      if @handout.save
        format.html { redirect_to @handout, notice: "Handout was successfully created." }
        format.json { render :show, status: :created, location: @handout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @handout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handouts/1 or /handouts/1.json
  def update
    authorize Handout, :update?
    respond_to do |format|
      if @handout.update(handout_params)
        format.html { redirect_to @handout, notice: "Handout was successfully updated." }
        format.json { render :show, status: :ok, location: @handout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @handout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handouts/1 or /handouts/1.json
  def destroy
    authorize Handout, :destroy?
    @handout.destroy
    respond_to do |format|
      format.html { redirect_to handouts_url, notice: "Handout was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def delete_document
    authorize Handout, :update?
    @my_document = ActiveStorage::Attachment.find(params[:id])
    #@my_receipt = SessionLog.find(params[:session_log_id]).receipt
    @my_document.purge_later
    flash[:success] = 'Document removed.'
    redirect_back(fallback_location: request.referer)
  end
  
  
  def activate
    authorize Handout, :update?
      if @handout.active
        flash[:warning] = 'Handout already active.'
        redirect_to handouts_path
        return
      else
        @handout.active = true
        if @handout.save
          flash[:success] = 'Handout activated'
          redirect_to handouts_path
          return
        else
          flash[:danger] = 'Handout not activated'
          redirect_to handouts_path
          return
        end
      end
  end
  def deactivate
    authorize Handout, :update?
      if !@handout.active
        flash[:warning] = 'Handout already inactive.'
        redirect_to handouts_path
        return
      else
        @handout.active = false
        if @handout.save
          flash[:success] = 'Handout deactivated'
          redirect_to handouts_path
          return
        else
          flash[:danger] = 'Handout not deactivated'
          redirect_to handouts_path
          return
        end
      end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handout
      @handout = Handout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def handout_params
      params.require(:handout).permit(:title, :description, :active, :document)
    end
end

app/helpers/handouts_helper.rb
module HandoutsHelper
end

app/views/handouts/_form.html.erb
<%= form_with(model: handout) do |form| %>
  <% if handout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(handout.errors.count, "error") %> prohibited this handout from being saved:</h2>

      <ul>
        <% handout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <% if handout.document.attached? %>
    <% if handout[:id].nil? %>
      <p>You had selected a document, but we need you to select it again. We're working on improving this, sorry!</p>
      <%= form.file_field :document %>
    <% else %>
      <p>A document is attached. <%= link_to 'Delete Receipt', delete_document_handout_path(handout.document.id), method: "delete", data: {confirm: 'You are about to delete a document. Are you sure?'} %></p>
    <% end %>
  <% else %>
    <div class="field">
      <%= form.file_field :document %>
    </div>  
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/handouts/edit.html.erb
<h1>Editing Handout</h1>

<%= render 'form', handout: @handout %>

<%= link_to 'Show', @handout %> |
<%= link_to 'Back', handouts_path %>

app/views/handouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>
<hr />
<p>These handouts, memos, and other documents may assist in the implementation of PREP. If you have any questions about these, please don't hesitate to contact your State Coordinator or the Evaluation Team.</p>

<table class="apa">
  <thead>
    <tr>
      <th>Title</th>
      <% if current_user.has_role?(:technician) %>
        <th>Active?</th>
      <% end %>
      <th>Tools</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handouts.each do |handout| %>
      <tr>
        <td><%= handout.title %></td>
        <% if current_user.has_role?(:technician) %>
          <td>
            <% if handout.active? %>
              <input type="checkbox" checked="checked" id="checkboxr<% handout.id %>" name="checkboxr<% handout.id %>" value="1" disabled="true"><%= link_to '-', deactivate_handout_path(handout), method: :post %>
            <% else %>
              <input type="checkbox" id="checkboxr<% handout.id %>" name="checkboxr<% handout.id %>" value="0" disabled="true"><%= link_to '+', activate_handout_path(handout), method: :post %>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if handout.document.attached? %>
            <%= link_to '(Get)', rails_storage_proxy_path(handout.document, disposition: "attachment" ) %>
          <% end %>
          <% if current_user.has_role?(:technician) %>
            <%= link_to 'Show', handout %>
            <%= link_to 'Edit', edit_handout_path(handout) %>
            <%= link_to 'Destroy', handout, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <td><%= handout.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.has_role?(:technician) %>
  <%= link_to 'New Handout', new_handout_path %>
<% end %>

app/views/handouts/new.html.erb
<h1>New Handout</h1>

<%= render 'form', handout: @handout %>

<%= link_to 'Back', handouts_path %>

app/views/handouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @handout.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @handout.description %>
</p>

<%= link_to 'Edit', edit_handout_path(@handout) %> |
<%= link_to 'Back', handouts_path %>