config/routes.rb
Rails.application.routes.draw do

  resources :enrollment_session_logs
  resources :enrollments
  get 'cohorts/(:cohort_id)/roster', to: 'enrollments#roster', as: 'master_roster'
  
  get 'entry_surveys/recode', to: 'entry_surveys#recode', as: 'recode_entry_surveys'
  get 'exit_surveys/recode', to: 'exit_surveys#recode', as: 'recode_exit_surveys'
  get 'entry_surveys/recode/(:id)', to: 'entry_surveys#recode_one', as: 'recode_entry_survey'
  get 'exit_surveys/recode/(:id)', to: 'exit_surveys#recode_one', as: 'recode_exit_survey'
  resources :exit_surveys
  resources :entry_surveys
  get 'providers/(:id)/surveys', to: 'providers#survey_results', as: 'provider_surveys'
  
  resources :incentives
  resources :staff_training_surveys, except: [ :new ]
  resources :staff_training_events
  get 'new_staff_survey/(:lookup)', to: 'staff_training_surveys#new', as: 'new_staff_training_survey'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }

  resources :coho_downs do
    member do
      delete :delete_receipt
    end
  end

  resources :handouts do
    member do
      delete :delete_document
    end
  end
  
  resources :coho_down_attends
  
  resources :session_logs do
    member do
      delete :delete_receipt
    end
  end
  resources :coho_ups
  resources :cohorts
  resources :module_lookups
  resources :providers
  resources :grantees
  resources :session_modules
  get '/filters', to: 'filters#index', as: 'filters'
  post 'filters/:provider_id', to: 'filters#add', as: 'add_filter'
  delete 'filters/:id', to: 'filters#remove', as: 'remove_filter'
  
  get '/finalize_annual_data', to: 'providers#finalize', as: 'finalize_provider'

  get '/incentivize/:species/:variety/:fingerprint', to: 'incentives#record_fingerprint', as: 'incentive_fingerprint'

  get 'users/', to: 'users#index'

  post 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post 'users/:id/activate', to: 'users#activate', as: 'activate_user'

  post 'users/:id/decoordinate', to: 'users#decoordinate', as: 'decoordinate_user'
  post 'users/:id/coordinate', to: 'users#coordinate', as: 'coordinate_user'

  post 'users/:id/devicar', to: 'users#devicar', as: 'devicar_user'
  post 'users/:id/vicar', to: 'users#vicar', as: 'vicar_user'
  
  post 'users/:id/su_off', to: 'users#detechnician', as: 'detechnician_user'
  post 'users/:id/su_on', to: 'users#technician', as: 'technician_user'
  
  post 'users/:id/detestify', to: 'users#detestify', as: 'detestify_user'
  post 'users/:id/testify', to: 'users#testify', as: 'testify_user'

  post 'users/add_admin', to: 'users#add_site_admin_role', as: 'add_site_admin_for_user'
  post 'users/:id/del_admin/:pid', to: 'users#del_site_admin_role', as: 'del_site_admin_for_user'

  post 'users/add_facilitator', to: 'users#add_facilitator_role', as: 'add_facilitator_for_user'
  post 'users/:id/del_facilitator/:pid', to: 'users#del_facilitator_role', as: 'del_facilitator_for_user'

  get 'cohorts/:id/facilitate', to: 'cohorts#facilitate', as: 'facilitate'
  get 'cohorts/:id/survey', to: 'cohorts#survey', as: 'survey'
  get 'cohorts/:id/enroll', to: 'cohorts#enroll', as: 'enroll'

  post 'handouts/:id/deactivate', to: 'handouts#deactivate', as: 'deactivate_handout'
  post 'handouts/:id/activate', to: 'handouts#activate', as: 'activate_handout'

  post 'enrollments/:id/hide', to: 'enrollments#hide', as: 'hide_enrollment'
  
  get 'reports/registration', to: 'reports#user_registrations', as: 'registration_report'
  get 'reports/activity', to: 'reports#recent_changes', as: 'activity_report'
  get 'reports/at-a-glance', to: 'reports#visualize_cohorts', as: 'visualize_cohorts'
  get 'reports/daily-reach', to: 'reports#daily_reach', as: 'daily_reach'
  get 'reports/outcomes/activities', to: 'reports#outcomes_dashboard_activities', as: 'outcomes_dashboard_activities'
  get 'reports/outcomes/outcomes', to: 'reports#outcomes_dashboard_outcomes', as: 'outcomes_dashboard_outcomes'
  get 'reports/outcomes/demographics', to: 'reports#outcomes_dashboard_demographics', as: 'outcomes_dashboard_demographics'
  get 'reports/outcomes/aggregated', to: 'reports#outcomes_dashboard_aggregated', as: 'outcomes_dashboard_aggregated'
  

  
  get 'reports/cir', to: 'reports#mpr_helper', as: 'mpr_helper'
  get 'reports/ppr', to: 'reports#ppr', as: 'ppr'
  #get 'reports/pmms/ard/:pid/:cname', to: 'reports#pmms_ard_program', as: 'pmms_ard_program'
  #get 'reports/pmms/ard/', to: 'reports#pmms_ard_program_index', as: 'pmms_ard_program_index'
  get 'reports/pmms/surveys/:provider_id/:curriculum_initials', to: 'reports#pmms_surveys', as: 'participant_surveys'
  get 'reports/pmms/surveys', to: 'reports#pmms_survey_index', as: 'pmms_survey_index'
  
  get 'reports/ppr/csv/cbo', to: 'reports#ppr_csv_cbo', as: 'get_ppr_csv_cbo'
  get 'reports/ppr/csv/ahyd', to: 'reports#ppr_csv_ahyd', as: 'get_ppr_csv_ahyd'
  

  root 'pages#index'
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :provider
  has_paper_trail
  validates :name, presence: true
  validates :curriculum_choice, presence: true
  validates :intended_start, presence: true
  validates :intended_finish, presence: true, after_date: :intended_start
  validates :intended_setting, presence: true
  validates :intended_session_count, numericality: { greater_than: 0 }
  validates :intended_session_duration_minute, numericality: { greater_than: 0 }
  validates :intended_participants_ms, numericality: { greater_than_or_equal_to: 0 }
  validates :intended_participants_hs, numericality: { greater_than_or_equal_to: 0 }
  validates :healthy_relationship_material_add_curr_entirely, either_or: :healthy_relationship_material_add_curr_adhoc
  validates :adolescent_development_material_add_curr_entirely, either_or: :adolescent_development_material_add_curr_adhoc
  validates :financial_literacy_material_add_curr_entirely, either_or: :financial_literacy_material_add_curr_adhoc
  validates :par_child_comm_material_add_curr_entirely, either_or: :par_child_comm_material_add_curr_adhoc
  validates :edu_career_success_material_add_curr_entirely, either_or: :edu_career_success_material_add_curr_adhoc
  validates :healthy_life_skills_material_add_curr_entirely, either_or: :healthy_life_skills_material_add_curr_adhoc
  has_one :coho_up
  has_one :coho_down
  has_many :session_logs
  has_many :entry_surveys, through: :coho_up
  has_many :exit_surveys, through: :coho_up
  has_many :enrollments
  
  def initiates
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE').joins(:session_logs).uniq
  end 
  def newfaces
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE').where.missing(:session_logs).uniq
  end 
  def graduates
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE and graduate is TRUE').uniq
  end 
  def youth_initiates
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE and age < 18').joins(:session_logs)
  end 
  def youth_newfaces
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE and age < 18').where.missing(:session_logs)
  end 
  def adult_initiates
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE and age >= 18').joins(:session_logs)
  end 
  def adult_newfaces
    #self.cohort.enrollments.where(graduate: true).pluck(:id)
    self.enrollments.where('trashed is not TRUE and age >= 18').where.missing(:session_logs)
  end 
  def earliest_date
    result = Array.new()
    if self.coho_down.present?
      if self.coho_down.coho_down_attends.length > 0
        result.push(self.coho_down.coho_down_attends.order(:happened_on).first[:happened_on])
      end
    end
    if self.session_logs.present?
      result.push(self.session_logs.order(:happened_on).first[:happened_on])
    end
    result.sort.first
  end
  def latest_date
    result = Array.new()
    if self.coho_down.present?
      if self.coho_down.coho_down_attends.length > 0
        result.push(self.coho_down.coho_down_attends.order(:happened_on).last[:happened_on])
      end
    end
    if self.session_logs.present?
      result.push(self.session_logs.order(:happened_on).last[:happened_on])
    end
    result.sort.last
  end
end

app/controllers/coho_downs_controller.rb
class CohoDownsController < ApplicationController
  before_action :set_coho_down, only: %i[ show edit update destroy ]

  # GET /coho_downs or /coho_downs.json
  def index
    authorize CohoDown, :index?
    @coho_downs = policy_scope(CohoDown)
  end

  # GET /coho_downs/1 or /coho_downs/1.json
  def show
    authorize @coho_down, :retrieve?
  end

  # GET /coho_downs/new
  def new
    authorize CohoDown, :create?
    if params[:cohort_id].present? 
      if Cohort.find_by(id: params[:cohort_id]).present?
        if Cohort.find_by(id: params[:cohort_id]).coho_up.present?
          if Cohort.find_by(id: params[:cohort_id]).coho_down.present?
            flash[:warning] = 'Cohort already closed.'
            redirect_to cohorts_path
            return        
          else
            @my_cohort = Cohort.find_by(id: params[:cohort_id])
            @coho_down = CohoDown.new
            @coho_down[:cohort_id] = @my_cohort[:id]
            if @my_cohort.session_logs.present?
              if @my_cohort.uses_enrollment?
                @my_cohort.session_logs.order(:happened_on).each{ |e| @coho_down.coho_down_attends.build(happened_on: e[:happened_on], middleschool_headcount: e[:middleschool_headcount], newface_ms_headcount: e[:newface_ms_headcount], highschool_headcount: e[:highschool_headcount], newface_hs_headcount: e[:newface_hs_headcount]) }
                @coho_down[:total_initiated_ms] = @my_cohort.youth_initiates.length
                @coho_down[:total_initiated_hs] = @my_cohort.adult_initiates.length
                #@coho_down[:census_foster] = @my_cohort.
                #@coho_down[:census_homeless] = @my_cohort.
                #@coho_down[:census_pregnant_parenting] = @my_cohort.
                #@coho_down[:census_adjudication] = @my_cohort.
                @coho_down[:ppr_count_total] = @my_cohort.initiates.length
                @coho_down[:ppr_count_male] = @my_cohort.enrollments.where(gender_m: true).length
                @coho_down[:ppr_count_female] = @my_cohort.enrollments.where(gender_f: true).length
                @coho_down[:ppr_count_10_13] = @my_cohort.enrollments.where(age: 10 .. 13).length
                @coho_down[:ppr_count_14_19] = @my_cohort.enrollments.where(age: 14 .. 19).length
                @coho_down[:ppr_count_20] = @my_cohort.enrollments.where('age >= 20').length
                @coho_down[:ppr_count_preg_par] = @my_cohort.enrollments.where(preg_par: true).length
                #@coho_down[:ppr_count_juv_jus] = @my_cohort.
                #@coho_down[:ppr_count_foster] = @my_cohort.
                #@coho_down[:ppr_count_runaway] = @my_cohort.
                @coho_down[:ppr_count_lgbt] = @my_cohort.enrollments.where(lgbt: true).length
                #@coho_down[:ppr_count_total = @my_cohort.
              else
                #@my_cohort.session_logs.order(:happened_on).each{ |e| @coho_down.coho_down_attends.build(happened_on: e[:happened_on]) }
                @my_cohort.session_logs.order(:happened_on).each{ |e| @coho_down.coho_down_attends.build(happened_on: e[:happened_on], middleschool_headcount: e[:middleschool_headcount], newface_ms_headcount: e[:newface_ms_headcount], highschool_headcount: e[:highschool_headcount], newface_hs_headcount: e[:newface_hs_headcount]) }
              end
            end
            @enrollments = Enrollment.where(cohort_id: @coho_down[:cohort_id], trashed: false)
          end
        else
          flash[:warning] = 'Cohort not activated. We can only close active cohorts.'
          redirect_to cohorts_path
          return
        end
      else
        flash[:danger] = 'Cohort not found. Please select another cohort for activation.'
        redirect_to cohorts_path
        return
      end
    else
      flash[:danger] = 'Cohort not provided. Please select a cohort for activation.'
      redirect_to cohorts_path
      return
    end
  end

  # GET /coho_downs/1/edit
  def edit
    authorize @coho_down, :update?
  end

  # POST /coho_downs or /coho_downs.json
  def create
    authorize CohoDown, :create?
    @coho_down = CohoDown.new(coho_down_params)
    if @coho_down.save
        flash[:success] = 'Cohort closed.'
        redirect_to cohorts_path
        return
    else
        flash[:danger] = 'Something went wrong. Cohort not closed.'
        @my_cohort = Cohort.find_by(id: @coho_down[:cohort_id])
        @enrollments = Enrollment.where(cohort_id: :cohort_id, trashed: false)
        render :new
        return
    end
  end

  # PATCH/PUT /coho_downs/1 or /coho_downs/1.json
  def update
    authorize @coho_down, :update?
    respond_to do |format|
      if @coho_down.update(coho_down_params)
        format.html { redirect_to cohorts_path, notice: "Coho down was successfully updated." }
        format.json { render :show, status: :ok, location: @coho_down }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coho_down.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coho_downs/1 or /coho_downs/1.json
  def destroy
    authorize @coho_down, :destroy?
    @coho_down.destroy
    flash[:success] = "Closure destroyed."
    redirect_to cohorts_path    
  end
  def delete_receipt
    authorize @coho_down, :update?
    @my_receipt = ActiveStorage::Attachment.find(params[:id])
    #@my_receipt = SessionLog.find(params[:session_log_id]).receipt
    @my_receipt.purge_later
    flash[:success] = 'Receipt removed.'
    redirect_back(fallback_location: request.referer)
    return
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coho_down
      @coho_down = CohoDown.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coho_down_params
      params.require(:coho_down).permit(:cohort_id, :ppr_count_total, :total_graduated_ms, :total_graduated_hs, :total_initiated_ms, :total_initiated_hs, :total_hours_delivered, :program_complete, :census_foster, :census_homeless, :census_pregnant_parenting, :census_adjudication, :main_setting, :covid_virtualization, :receipt, :ppr_count_male, :ppr_count_female, :ppr_count_10_13, :ppr_count_14_19, :ppr_count_20, :ppr_count_preg_par, :ppr_count_juv_jus, :ppr_count_foster, :ppr_count_runaway, :ppr_count_lgbt, :rationale, graduate_ids: [], coho_down_attends_attributes: [:id, :_destroy, :coho_down_id, :happened_on, :middleschool_headcount, :highschool_headcount, :newface_ms_headcount, :newface_hs_headcount])
    end
end

app/helpers/coho_downs_helper.rb
module CohoDownsHelper
end

app/views/coho_downs/_form.html.erb
<% content_for :header do %>
  <script>
      class addFields {
        constructor() {
          this.links = document.querySelectorAll(".add_fields");
          this.iterateLinks();
        }

        iterateLinks() {
          if (this.links.length === 0) return;
          this.links.forEach((link) => {
            link.addEventListener("click", (e) => {
              this.handleClick(link, e);
            });
          });
        }

        handleClick(link, e) {
          if (!link || !e) return;
          e.preventDefault();
          let time = new Date().getTime();
          let linkId = link.dataset.id;
          let regexp = linkId ? new RegExp(linkId, "g") : null;
          let newFields = regexp ? link.dataset.fields.replace(regexp, time) : null;
          //newFields ? link.insertAdjacentHTML("beforebegin", newFields) : null;
          if (newFields) {
            link.insertAdjacentHTML("beforebegin", newFields);
            $('.datepicker').datepicker( { dateFormat: 'yy-mm-dd' })
          } else {
            null;
          }
        }
        
      }
      window.addEventListener("load", () => new addFields());
      class removeFields {
        constructor() {
          this.iterateLinks();
        }

        iterateLinks() {
          document.addEventListener("click", (e) => {
            if (e.target && e.target.className == "remove_fields") {
              this.handleClick(e.target, e);
            }
          });
        }

        handleClick(link, e) {
          if (!link || !e) return;
          e.preventDefault();
          let fieldParent = link.closest(".nested-fields");
          let deleteField = fieldParent
            ? fieldParent.querySelector('input[type="hidden"]')
            : null;
          if (deleteField) {
            deleteField.value = 1;
            fieldParent.style.display = "none";
          }
        }
      }

      window.addEventListener("load", () => new removeFields());


    var ready = function() {
      $('.datepicker').datepicker( { dateFormat: 'yy-mm-dd' } );
    };
    $(document).ready(ready);
  </script>
<% end %>

<%= form_with(model: coho_down, local: true) do |f| %>
  <% if coho_down.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coho_down.errors.count, "error") %> prohibited this coho_down from being saved:</h2>

      <ul>
        <% coho_down.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :cohort_id, readonly: true, hidden: true %>
  </div>
  
  <div class="d-flex flex-column align-items-start">
    <div class="d-flex flex-column align-items-end">
      <div class="field">
        <%= f.label :total_graduated_ms %>
        <%= f.number_field :total_graduated_ms, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :total_graduated_hs %>
        <%= f.number_field :total_graduated_hs, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :total_initiated_ms %>
        <%= f.number_field :total_initiated_ms, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :total_initiated_hs %>
        <%= f.number_field :total_initiated_hs, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :total_hours_delivered %>
        <%= f.number_field :total_hours_delivered, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :program_complete %>
        <%= f.check_box :program_complete %>
      </div>
      
      <div class="field">
        <%= f.label :rationale %>
        <%= f.text_field :rationale, {size: 25, maxlength: 255} %>
      </div>

      <div class="field">
        <%= f.label :census_foster %>
        <%= f.number_field :census_foster, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :census_homeless %>
        <%= f.number_field :census_homeless, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :census_pregnant_parenting %>
        <%= f.number_field :census_pregnant_parenting, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :census_adjudication %>
        <%= f.number_field :census_adjudication, required: true, min:0, size: 2 %>
      </div>

      <div class="field">
        <%= f.label :main_setting %>
        <%= f.select(:main_setting, ['In School, during school', 'In School, after school', 'Community-Based Organization', 'Clinic', 'Foster Care Setting', 'Juvenile Detention Setting', 'Residential Mental Health Treatment Facility', 'Virtual', 'Other'], {},{ prompt: 'Select one', required: true }) %>
      </div>

      <div class="field">
        <%= f.label :covid_virtualization %>
        <%= f.check_box :covid_virtualization %>
      </div>
    </div>
  </div>

  <h2>Attendance</h2>
  <fieldset>
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        <p>Date</p>
      </div>
      <div class="col-sm-2">
        <p><%= f.label :middleschool %></p>
      </div>
      <div class="col-sm-2">
        <p><i>New</i> <%= f.label :middleschool %></p>
      </div>
      <div class="col-sm-2">
        <p><%= f.label :highschool %></p>
      </div>
      <div class="col-sm-2">
        <p><i>New</i> <%= f.label :highschool %></p>
      </div>
      <div class="col-sm-2">
        <p>Delete Row</p>
      </div>
    </div>
    <%= f.fields_for :coho_down_attends do |coho_down_attends_form| %>
      <%= render 'coho_down_attend_fields', f: coho_down_attends_form %>
    <% end %>
    
        <%= link_to_add_fields "Add Row", f, :coho_down_attends %>
    
  </div>
  </fieldset>

  <h2>Cohort Reach</h2>
  <p>Based on the final status of the cohort, please specify how many participants fall under the following demographics:<p>
  
  <div class="d-flex flex-column align-items-start">
    <div class="d-flex flex-column align-items-end">
      <div class="field">
        <b><%= f.label :ppr_count_total %></b>
        <%= f.number_field :ppr_count_total, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_male %>
        <%= f.number_field :ppr_count_male, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_female %>
        <%= f.number_field :ppr_count_female, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_10_13 %>
        <%= f.number_field :ppr_count_10_13, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_14_19 %>
        <%= f.number_field :ppr_count_14_19, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_20 %>
        <%= f.number_field :ppr_count_20, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_preg_par %>
        <%= f.number_field :ppr_count_preg_par, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_juv_jus %>
        <%= f.number_field :ppr_count_juv_jus, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_foster %>
        <%= f.number_field :ppr_count_foster, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_runaway %>
        <%= f.number_field :ppr_count_runaway, required: true, min: 0, size: 2  %>
      </div>
      <div class="field">
        <%= f.label :ppr_count_lgbt %>
        <%= f.number_field :ppr_count_lgbt, required: true, min: 0, size: 2  %>
      </div>
    </div>
  </div>

  <h2>Receipts</h2>
  <p>Attach a file that documents this cohort's attendance. Any format of any file will do: even a picture of a gradebook on your phone, as long as it is legible!
  <br />As a reminder, you can use the <%= link_to 'template', '/cohort-participation-template.xlsx', download: "template.xlsx" %> if your site has no established format for these data.</p>
  <% if coho_down.receipt.attached? %>
    <% if coho_down[:id].nil? %>
      <p>You had selected a receipt, but we need you to select it again. We're working on improving this, sorry!</p>
      <%= f.file_field :receipt %>
    <% else %>
      <p>A receipt is attached. <%= link_to 'Delete Receipt', delete_receipt_coho_down_path(coho_down.receipt.id), method: "delete", data: {confirm: 'You are about to delete a receipt. Are you sure?'} %></p>
    <% end %>
  <% else %>
    <div class="field">
      <%= f.file_field :receipt %>
    </div>  
  <% end %>

  <% if coho_down.cohort.uses_enrollment? %>
    <h2>Graduates</h2>
    <p>Please note who graduated by checking the graduates:<br />(Note: we have <%= @my_cohort.session_log_ids.present? ? @my_cohort.session_log_ids.length.to_s : "0" %> sessions on file)</p>
    <div class="field">
      <%= f.collection_check_boxes :graduate_ids, @enrollments, :id, :quick_name do |c| %>
        <%= c.check_box %>
        <%= c.label + " who attended " + (c.object.session_log_ids.present? ? c.object.session_log_ids.length.to_s : "0") + " sessions" %>
        <br />
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <hr />

<% end %>

app/views/coho_downs/edit.html.erb
<h1>Editing Cohort Closure</h1>

<%= render 'form', coho_down: @coho_down %>

<%= link_to 'Show', @coho_down %> |
<%= link_to 'Back', coho_downs_path %>

app/views/coho_downs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coho Downs</h1>

<table>
  <thead>
    <tr>
      <th>Period</th>
      <th>Provider</th>
      <th colspan="2">Cohort</th>
      <th>Total graduated ms</th>
      <th>Total graduated hs</th>
      <th>Total initiated ms</th>
      <th>Total initiated hs</th>
      <th>Total hours delivered</th>
      <th>Program complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coho_downs.each do |coho_down| %>
      <tr>
        <td><%= coho_down.cohort.period %></td>
        <td><%= coho_down.cohort.provider.long_name %></td>
        <td><%= coho_down.cohort.name %></td>
        <td><%= coho_down.cohort.extra_name %></td>
        <td><%= coho_down.total_hours_delivered %></td>
        <td><%= coho_down.program_complete %></td>
        <td><%= coho_down.census_foster %></td>
        <td><%= coho_down.census_homeless %></td>
        <td><%= coho_down.census_pregnant_parenting %></td>
        <td><%= coho_down.census_adjudication %></td>
        <td><%= link_to 'Show', coho_down %></td>
        <td><%= link_to 'Edit', edit_coho_down_path(coho_down) %></td>
        <td><%= link_to 'Destroy', coho_down, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coho Down', new_coho_down_path %>

app/views/coho_downs/new.html.erb
<h1>Close a Cohort</h1>

<h2>Review</h2>
<p>Before continuing with closure, please review the cohort information below:</p>
<div class="container border border-info">
  <%= render 'cohorts/snapshot', cohort: @my_cohort %>
</div>
<p>If needed, please <%= link_to 'update', edit_cohort_path(@my_cohort[:id]) %> the cohort information prior to closure.</p>

<h2>Documentation</h2>
<p>Please provide some information about this cohort.</p>
<%= render 'form', coho_down: @coho_down %>



<%= link_to 'Back', coho_downs_path %>