config/routes.rb
Rails.application.routes.draw do

  resources :enrollment_session_logs
  resources :enrollments
  get 'cohorts/(:cohort_id)/roster', to: 'enrollments#roster', as: 'master_roster'
  
  get 'entry_surveys/recode', to: 'entry_surveys#recode', as: 'recode_entry_surveys'
  get 'exit_surveys/recode', to: 'exit_surveys#recode', as: 'recode_exit_surveys'
  get 'entry_surveys/recode/(:id)', to: 'entry_surveys#recode_one', as: 'recode_entry_survey'
  get 'exit_surveys/recode/(:id)', to: 'exit_surveys#recode_one', as: 'recode_exit_survey'
  resources :exit_surveys
  resources :entry_surveys
  get 'providers/(:id)/surveys', to: 'providers#survey_results', as: 'provider_surveys'
  
  resources :incentives
  resources :staff_training_surveys, except: [ :new ]
  resources :staff_training_events
  get 'new_staff_survey/(:lookup)', to: 'staff_training_surveys#new', as: 'new_staff_training_survey'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations'
  }

  resources :coho_downs do
    member do
      delete :delete_receipt
    end
  end

  resources :handouts do
    member do
      delete :delete_document
    end
  end
  
  resources :coho_down_attends
  
  resources :session_logs do
    member do
      delete :delete_receipt
    end
  end
  resources :coho_ups
  resources :cohorts
  resources :module_lookups
  resources :providers
  resources :grantees
  resources :session_modules
  get '/filters', to: 'filters#index', as: 'filters'
  post 'filters/:provider_id', to: 'filters#add', as: 'add_filter'
  delete 'filters/:id', to: 'filters#remove', as: 'remove_filter'
  
  get '/finalize_annual_data', to: 'providers#finalize', as: 'finalize_provider'

  get '/incentivize/:species/:variety/:fingerprint', to: 'incentives#record_fingerprint', as: 'incentive_fingerprint'

  get 'users/', to: 'users#index'

  post 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate_user'
  post 'users/:id/activate', to: 'users#activate', as: 'activate_user'

  post 'users/:id/decoordinate', to: 'users#decoordinate', as: 'decoordinate_user'
  post 'users/:id/coordinate', to: 'users#coordinate', as: 'coordinate_user'

  post 'users/:id/devicar', to: 'users#devicar', as: 'devicar_user'
  post 'users/:id/vicar', to: 'users#vicar', as: 'vicar_user'
  
  post 'users/:id/su_off', to: 'users#detechnician', as: 'detechnician_user'
  post 'users/:id/su_on', to: 'users#technician', as: 'technician_user'
  
  post 'users/:id/detestify', to: 'users#detestify', as: 'detestify_user'
  post 'users/:id/testify', to: 'users#testify', as: 'testify_user'

  post 'users/add_admin', to: 'users#add_site_admin_role', as: 'add_site_admin_for_user'
  post 'users/:id/del_admin/:pid', to: 'users#del_site_admin_role', as: 'del_site_admin_for_user'

  post 'users/add_facilitator', to: 'users#add_facilitator_role', as: 'add_facilitator_for_user'
  post 'users/:id/del_facilitator/:pid', to: 'users#del_facilitator_role', as: 'del_facilitator_for_user'

  get 'cohorts/:id/facilitate', to: 'cohorts#facilitate', as: 'facilitate'
  get 'cohorts/:id/survey', to: 'cohorts#survey', as: 'survey'
  get 'cohorts/:id/enroll', to: 'cohorts#enroll', as: 'enroll'

  post 'handouts/:id/deactivate', to: 'handouts#deactivate', as: 'deactivate_handout'
  post 'handouts/:id/activate', to: 'handouts#activate', as: 'activate_handout'

  post 'enrollments/:id/hide', to: 'enrollments#hide', as: 'hide_enrollment'
  
  get 'reports/registration', to: 'reports#user_registrations', as: 'registration_report'
  get 'reports/activity', to: 'reports#recent_changes', as: 'activity_report'
  get 'reports/at-a-glance', to: 'reports#visualize_cohorts', as: 'visualize_cohorts'
  get 'reports/daily-reach', to: 'reports#daily_reach', as: 'daily_reach'
  get 'reports/outcomes/activities', to: 'reports#outcomes_dashboard_activities', as: 'outcomes_dashboard_activities'
  get 'reports/outcomes/outcomes', to: 'reports#outcomes_dashboard_outcomes', as: 'outcomes_dashboard_outcomes'
  get 'reports/outcomes/demographics', to: 'reports#outcomes_dashboard_demographics', as: 'outcomes_dashboard_demographics'
  get 'reports/outcomes/aggregated', to: 'reports#outcomes_dashboard_aggregated', as: 'outcomes_dashboard_aggregated'
  

  
  get 'reports/cir', to: 'reports#mpr_helper', as: 'mpr_helper'
  get 'reports/ppr', to: 'reports#ppr', as: 'ppr'
  #get 'reports/pmms/ard/:pid/:cname', to: 'reports#pmms_ard_program', as: 'pmms_ard_program'
  #get 'reports/pmms/ard/', to: 'reports#pmms_ard_program_index', as: 'pmms_ard_program_index'
  get 'reports/pmms/surveys/:provider_id/:curriculum_initials', to: 'reports#pmms_surveys', as: 'participant_surveys'
  get 'reports/pmms/surveys', to: 'reports#pmms_survey_index', as: 'pmms_survey_index'
  
  get 'reports/ppr/csv/cbo', to: 'reports#ppr_csv_cbo', as: 'get_ppr_csv_cbo'
  get 'reports/ppr/csv/ahyd', to: 'reports#ppr_csv_ahyd', as: 'get_ppr_csv_ahyd'
  

  root 'pages#index'
end

app/controllers/reports_controller.rb
require 'csv'

class ReportsController < ApplicationController
  def user_registrations
    authorize :report, :view?
   
    @active_users =  User.where(active: true).without_role(:state_coordinator).without_role(:technician).with_role(:site_admin, :any).or(
                     User.where(active: true).without_role(:state_coordinator).without_role(:technician).with_role(:facilitator, :any))
                     .uniq

    @ghost_users =  User.where(active: true).without_role(:state_coordinator).without_role(:vicar).without_role(:technician).without_role(:site_admin, :any).without_role(:facilitator, :any)

    @inactive_users = User.where(active: false)
  end
  
  def recent_changes
    authorize :report, :view?
    #recent_changes_A = PaperTrail::Version.order(:created_at).where("created_at >= ? AND CAST(whodunnit AS INT) NOT IN (?)",  Time.current - 1.week, User.with_role(:technician).pluck(:id))
    #recent_changes_B = PaperTrail::Version.order(:created_at).where("CAST(whodunnit AS INT) NOT IN (?)", User.with_role(:technician).pluck(:id)).last(10)
    #@recent_changes = (recent_changes_A + recent_changes_B).uniq
    
    @recent_cohort_changes = PaperTrail::Version.joins('LEFT OUTER JOIN "users" ON CAST("versions"."whodunnit" AS INT) = "users"."id"').order("versions.created_at": :desc).where("versions.item_type = ? AND versions.created_at >= ? AND CAST(versions.whodunnit AS INT) NOT IN (?)",  "Cohort", Time.current - 1.week, User.with_role(:technician).or(User.with_role(:test)).pluck(:id)).select("versions.*, users.email as email")
    @recent_cohort_activations = PaperTrail::Version.joins('LEFT OUTER JOIN "users" ON CAST("versions"."whodunnit" AS INT) = "users"."id"').order("versions.created_at": :desc).where("versions.item_type = ? AND versions.created_at >= ? AND CAST(versions.whodunnit AS INT) NOT IN (?)",  "CohoUp", Time.current - 1.week, User.with_role(:technician).or(User.with_role(:test)).pluck(:id)).select("versions.*, users.email as email")
    @recent_cohort_closures = PaperTrail::Version.joins('LEFT OUTER JOIN "users" ON CAST("versions"."whodunnit" AS INT) = "users"."id"').order("versions.created_at": :desc).where("versions.item_type = ? AND versions.created_at >= ? AND CAST(versions.whodunnit AS INT) NOT IN (?)",  "CohoDown", Time.current - 1.week, User.with_role(:technician).or(User.with_role(:test)).pluck(:id)).select("versions.*, users.email as email")
    @recent_session_logs = PaperTrail::Version.joins('LEFT OUTER JOIN "users" ON CAST("versions"."whodunnit" AS INT) = "users"."id"').order("versions.created_at": :desc).where("versions.item_type = ? AND versions.created_at >= ? AND CAST(versions.whodunnit AS INT) NOT IN (?)",  "SessionLog", Time.current - 1.week, User.with_role(:technician).or(User.with_role(:test)).pluck(:id)).select("versions.*, users.email as email")
    
    @recent_cohorts = Cohort.where("id IN (?)", @recent_cohort_changes.pluck(:item_id))
    @recent_activation_cohorts = CohoUp.where("id IN (?)", @recent_cohort_activations.pluck(:item_id))
    @recent_closure_cohorts = CohoDown.where("id IN (?)", @recent_cohort_closures.pluck(:item_id))
    @recent_session_log_cohorts = SessionLog.where("id IN (?)", @recent_session_logs.pluck(:item_id))
  end
  
  def visualize_cohorts
    authorize :report, :visualize?
    @scoped_cohorts = policy_scope(Cohort).joins(:coho_up).joins('LEFT OUTER JOIN "providers" ON "cohorts"."provider_id" = "providers"."id"').select("cohorts.*, CAST(providers.pmms_aggregate_name ~ 'AHYD' AS INT) as isAHYD, providers.long_name").where("cohorts.name not similar to ? AND providers.long_name not similar to ?", "%[Tt][Ee][Ss][Tt]%", "%[Tt][Ee][Ss][Tt]%").order("isAHYD DESC, providers.long_name, cohorts.name, cohorts.extra_name, intended_start")
  end
  
  def outcomes_dashboard_activities
    #authorize :report, :view?
    authorize :report, :mpr_helper?

    if params[:start].nil?
      @window_start = "2023-01-01"
    else
      @window_start = params[:start]
    end
    if params[:stop].nil?
      @window_stop = "2023-06-30"
    else
      @window_stop = params[:stop]
    end

    y, m, d = @window_start.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Start date was invalid.'
      redirect_to root_path
    else
      @window_start = Date.new(y.to_i, m.to_i, d.to_i)
    end

    y, m, d = @window_stop.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Stop date was invalid.'
      redirect_to root_path
    else
      @window_stop = Date.new(y.to_i, m.to_i, d.to_i)
    end
    
    window_sessions = SessionLog.where(happened_on: @window_start .. @window_stop)
    window_attends = CohoDownAttend.where(happened_on: @window_start .. @window_stop)
    window_cohort_ids = (window_sessions.pluck(:cohort_id) + window_attends.map{|i| i.cohort.id}.sort.uniq).sort.uniq
    window_provider_ids = Cohort.where(id: window_cohort_ids).pluck(:provider_id).sort.uniq
    window_entry = EntrySurvey.where(happened_on: @window_start .. @window_stop)
    window_exit = ExitSurvey.where(happened_on: @window_start .. @window_stop)
    @included_providers = policy_scope(Provider).where(id: window_provider_ids)
    @included_cohorts = policy_scope(Cohort).where(id: window_cohort_ids)
    @included_entry = EntrySurvey.where(id: @included_cohorts.map{|i| i.entry_surveys.map{|j| j.id} }.flatten.sort.uniq)
    @included_exit = ExitSurvey.where(id: @included_cohorts.map{|i| i.exit_surveys.map{|j| j.id} }.flatten.sort.uniq)
    
    @poolNames = @included_providers.pluck(:pmms_aggregate_name, :period).sort.uniq
    
    
    #@included_cohorts = @included_providers.map{|i| policy_scope(Cohort).where(provider_id: i).where(id: window_cohort_ids)}
    #@included_entry = @included_cohorts.map{|i| i.entry_surveys}
    #@included_exit = @included_cohorts.map{|i| i.exit_surveys}
    
    
    
    #included_cohorts = policy_scope(Cohort).where(id: CohoUp.where(magic_code: included_entry.pluck(:magic).sort.uniq).pluck(:cohort_id).sort.uniq).or(Cohort.where(id: CohoUp.where(magic_code: included_exit.pluck(:magic).sort.uniq).pluck(:cohort_id).sort.uniq))
    #included_providers = policy_scope(Provider).where(id: included_cohorts.pluck(:provider_id).sort.uniq).order(pmms_aggregate_name: :asc, long_name: :asc)
    
  
  end
  def outcomes_dashboard_outcomes
    authorize :report, :view?
    if params[:start].nil?
      @window_start = "2023-01-01"
    else
      @window_start = params[:start]
    end
    if params[:stop].nil?
      @window_stop = "2023-06-30"
    else
      @window_stop = params[:stop]
    end

    y, m, d = @window_start.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Start date was invalid.'
      redirect_to root_path
    else
      @window_start = Date.new(y.to_i, m.to_i, d.to_i)
    end

    y, m, d = @window_stop.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Stop date was invalid.'
      redirect_to root_path
    else
      @window_stop = Date.new(y.to_i, m.to_i, d.to_i)
    end
    
    window_sessions = SessionLog.where(happened_on: @window_start .. @window_stop)
    window_attends = CohoDownAttend.where(happened_on: @window_start .. @window_stop)
    window_cohort_ids = (window_sessions.pluck(:cohort_id) + window_attends.map{|i| i.cohort.id}.sort.uniq).sort.uniq
    window_provider_ids = Cohort.where(id: window_cohort_ids).pluck(:provider_id).sort.uniq
    window_entry = EntrySurvey.where(happened_on: @window_start .. @window_stop)
    window_exit = ExitSurvey.where(happened_on: @window_start .. @window_stop)
    @included_providers = policy_scope(Provider).where(id: window_provider_ids)
    @included_cohorts = policy_scope(Cohort).where(id: window_cohort_ids)
    @included_entry = EntrySurvey.where(id: @included_cohorts.map{|i| i.entry_surveys.map{|j| j.id} }.flatten.sort.uniq)
    @included_exit = ExitSurvey.where(id: @included_cohorts.map{|i| i.exit_surveys.map{|j| j.id} }.flatten.sort.uniq)
    
    @poolNames = @included_providers.pluck(:pmms_aggregate_name, :period).sort.uniq
    
    
    #@included_cohorts = @included_providers.map{|i| policy_scope(Cohort).where(provider_id: i).where(id: window_cohort_ids)}
    #@included_entry = @included_cohorts.map{|i| i.entry_surveys}
    #@included_exit = @included_cohorts.map{|i| i.exit_surveys}
    
    
    
    #included_cohorts = policy_scope(Cohort).where(id: CohoUp.where(magic_code: included_entry.pluck(:magic).sort.uniq).pluck(:cohort_id).sort.uniq).or(Cohort.where(id: CohoUp.where(magic_code: included_exit.pluck(:magic).sort.uniq).pluck(:cohort_id).sort.uniq))
    #included_providers = policy_scope(Provider).where(id: included_cohorts.pluck(:provider_id).sort.uniq).order(pmms_aggregate_name: :asc, long_name: :asc)
    
  
  end
  def outcomes_dashboard_demographics
    authorize :report, :view?
    if params[:start].nil?
      @window_start = "2023-01-01"
    else
      @window_start = params[:start]
    end
    if params[:stop].nil?
      @window_stop = "2023-06-30"
    else
      @window_stop = params[:stop]
    end

    y, m, d = @window_start.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Start date was invalid.'
      redirect_to root_path
    else
      @window_start = Date.new(y.to_i, m.to_i, d.to_i)
    end

    y, m, d = @window_stop.split '-'
    if !Date.valid_date? y.to_i, m.to_i, d.to_i
      flash[:danger] = 'Stop date was invalid.'
      redirect_to root_path
    else
      @window_stop = Date.new(y.to_i, m.to_i, d.to_i)
    end
    
    window_sessions = SessionLog.where(happened_on: @window_start .. @window_stop)
    window_attends = CohoDownAttend.where(happened_on: @window_start .. @window_stop)
    window_cohort_ids = (window_sessions.pluck(:cohort_id) + window_attends.map{|i| i.cohort.id}.sort.uniq).sort.uniq
    window_provider_ids = Cohort.where(id: window_cohort_ids).pluck(:provider_id).sort.uniq

app/views/reports/daily_reach.html.erb
<% content_for :header do %>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.load('current', {'packages':['line']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Day', 'Total'],
        <% @date_counts.each do |dc| %>
        [ new Date(<%= dc[0].year %>, <%= dc[0].month - 1 %>, <%= dc[0].day %>), 
          <%= dc[1] %>
        ]<%= dc != @date_counts.last ? "," : "" %>
        <% end %>
        ]);

        var options = {
          chart: {
            title: 'Statewide Participation',
            subtitle: 'Daily session log totals across all cohorts',
          }
        };

        var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
        
        
        
              var data = new google.visualization.DataTable();
      data.addColumn('date', 'Day');
      data.addColumn('number', 'Initiates');


      data.addRows([
        <% @date_totals.each do |dc| %>
        [ new Date(<%= dc[0].year %>, <%= dc[0].month - 1 %>, <%= dc[0].day %>), 
          <%= dc[1] %>
        ]<%= dc != @date_totals.last ? "," : "" %>
        <% end %>

      ]);

      var options = {
        chart: {
          title: 'Cumulative Participants',
          subtitle: 'Based on Statewide Statewide Session Log Initiate Counts'
        },
        width: 900,
        height: 500
      };

      var chart = new google.charts.Line(document.getElementById('linechart_material'));

      chart.draw(data, google.charts.Line.convertOptions(options));
      }
  </script>
<% end %>
<h1>Statewide Reach</h1>
<div id="columnchart_material"></div>
<h1>Statewide Recruitment</h1>
<div id="linechart_material"></div>

app/views/reports/pmms_survey_index.html.erb
<h1>PMMS Participant Survey Reports</h1>
<p>Select a report below</p>
<p> Note: You can select date range  in the next page </p>
<table class="apa">
  <tr>
    <th>PMMS Provider</th>
    <th colspan="4">
      <div class="row" style="border-bottom: 1px solid black">
        <div class="col">PMMS Programs</div>
      </div>
      <div class="row">
        <div class="col">MAD</div>
        <div class="col">MPC</div>
        <div class="col">BPBRBP</div>
        <div class="col">LN</div>
      </div>
    </th>
  </tr>
  <% @index_table.each do |r| %>
    <tr>
      <td><%= r[:pool] %></td>
      <td><%= r[:countMAD] > 0 ? link_to("✓", participant_surveys_path(provider_id: r[:pid], curriculum_initials: "MAD")): "—" %></td>
      <td><%= r[:countMPC] > 0 ? link_to("✓", participant_surveys_path(provider_id: r[:pid], curriculum_initials: "MPC")): "—" %></td>
      <td><%= r[:countBPBRBP] > 0 ? link_to("✓", participant_surveys_path(provider_id: r[:pid], curriculum_initials: "BPBRBP")): "—" %></td>
      <td><%= r[:countLN] > 0 ? link_to("✓", participant_surveys_path(provider_id: r[:pid], curriculum_initials: "LN")): "—" %></td>
    </tr>
  <% end %>
</table>
<p>If cohorts were observed for the provider and curriculum during the period, then a report link will be generated.<br />There may or may not be surveys within that report.</p>

app/views/reports/ppr.html.erb
<% content_for :header do %>
  <script>
    var ready = function() {
          $('.datepicker').datepicker( { dateFormat: 'yy-mm-dd' } );
    };
    $(document).ready(ready);
    //$(document).on('turbolinks:load', ready); 
  </script>
<% end %>

<h1>Range selection</h1>
      <div class="field">
        <%= form_tag(ppr_path, method: :get) do %>
          <%= text_field_tag :start, params[:start], required: true, class: "datepicker" %>
          <%= text_field_tag :stop, params[:stop], required: true, class: "datepicker" %>
          <%= submit_tag ("Go") %>
        <% end %>
      </div>

<h1 style="text-align: center">Personal Responsibility Education Program<br />SAMPLE PROGRAM INDICATORS CHART<br />Attachment 2<br /></h1>
<p>Please note: realtime data are subject to change and cleaning.</p>

<p><b>Grantee:</b> GA-PREP<br />
<b>Grant:</b> GA-PREP<br />
<b>Activity Period:</b> <%= @window_start.strftime("%-m/%-d/%Y") %> - <%= @window_stop.strftime("%-m/%-d/%Y") %><br />
<b>Community Based Organization Participant Data</b> <%= link_to "Download", get_ppr_csv_cbo_path(start: @window_start, stop: @window_stop) %></p>

<table class="apa">
<tr>
  <th>Site or Implementation Provider</th>
  <th>Total # Initiated</th>
  <th>Total # Completed</th>
  <th># Male</th>
  <th># Female</th>
  <th># Ages 10 to 14</th>
  <th># Ages 15 to 19</th>
  <th># Ages 20</th>
  <th># Pregnant and Parenting</th>
  <th>#JJ</th>
  <th>#FC</th>
  <th>#RHY</th>
  <th>#LGBT</th>
</tr>
<% @cbo_data.each do |cbo| %>
  <tr>
    <td><b><%= cbo[:n_provider] %></b><br /><%= cbo[:n_site] %><%= cbo[:n_unclosed] ? "*" : "" %></td>
    <td><%= cbo[:n_initiated] %></td>
    <td><%= cbo[:n_graduated] %></td>
    <td><%= cbo[:n_male] %></td>
    <td><%= cbo[:n_female] %></td>
    <td><%= cbo[:n_10] %></td>
    <td><%= cbo[:n_14] %></td>
    <td><%= cbo[:n_20] %></td>
    <td><%= cbo[:n_preg] %></td>
    <td><%= cbo[:n_justice] %></td>
    <td><%= cbo[:n_foster] %></td>
    <td><%= cbo[:n_runaway] %></td>
    <td><%= cbo[:n_lgbt] %></td>
  </tr>
<% end %>
  <tr>
    <td><b><span style="color: red">Total</span></b></td>
    <td><b><%= @cbo_data.pluck(:n_initiated).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_graduated).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_male).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_female).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_10).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_14).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_20).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_preg).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_justice).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_foster).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_runaway).sum %></b></td>
    <td><b><%= @cbo_data.pluck(:n_lgbt).sum %></b></td>
  </tr>
</table>
<p>* Contains data from unclosed (usually ongoing) cohorts</p>
<p>JJ - youth in juvenile justice<br />
FC - Youth in foster care<br />
RHY - Runaway and homeless youth<br />
LGBT - Lesbian, gay, bisexual, transgendered youth
</p>


<p><b>Grantee:</b> GA-PREP<br />
<b>Grant:</b> GA-PREP<br />
<b>Activity Period:</b> <%= @window_start.strftime("%-m/%-d/%Y") %> - <%= @window_stop.strftime("%-m/%-d/%Y") %><br />
<b>Georgia Department of Public Health Participant Data</b> <%= link_to "Download", get_ppr_csv_ahyd_path(start: @window_start, stop: @window_stop) %></p>

<table class="apa">
<tr>
  <th>Site or Implementation Provider</th>
  <th>Total # Initiated</th>
  <th>Total # Completed</th>
  <th># Male</th>
  <th># Female</th>
  <th># Ages 10 to 14</th>
  <th># Ages 15 to 19</th>
  <th># Ages 20</th>
  <th># Pregnant and Parenting</th>
  <th>#JJ</th>
  <th>#FC</th>
  <th>#RHY</th>
  <th>#LGBT</th>
</tr>
<% @ahyd_data.each do |ahyd| %>
  <tr>
    <td><b><%= ahyd[:n_provider] %></b><br /><%= ahyd[:n_site] %><%= ahyd[:n_unclosed] ? "*" : "" %></td>
    <td><%= ahyd[:n_initiated] %></td>
    <td><%= ahyd[:n_graduated] %></td>
    <td><%= ahyd[:n_male] %></td>
    <td><%= ahyd[:n_female] %></td>
    <td><%= ahyd[:n_10] %></td>
    <td><%= ahyd[:n_14] %></td>
    <td><%= ahyd[:n_20] %></td>
    <td><%= ahyd[:n_preg] %></td>
    <td><%= ahyd[:n_justice] %></td>
    <td><%= ahyd[:n_foster] %></td>
    <td><%= ahyd[:n_runaway] %></td>
    <td><%= ahyd[:n_lgbt] %></td>
  </tr>
<% end %>
  <tr>
    <td><b><span style="color: red">Total</span></b></td>
    <td><b><%= @ahyd_data.pluck(:n_initiated).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_graduated).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_male).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_female).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_10).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_14).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_20).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_preg).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_justice).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_foster).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_runaway).sum %></b></td>
    <td><b><%= @ahyd_data.pluck(:n_lgbt).sum %></b></td>
  </tr>
</table>
<p>* Contains data from unclosed (usually ongoing) cohorts</p>
<p>JJ - youth in juvenile justice<br />
FC - Youth in foster care<br />
RHY - Runaway and homeless youth<br />
LGBT - Lesbian, gay, bisexual, transgendered youth
</p>

app/views/reports/ppr_csv.csv.erb
<%= CSV.generate_line(['provider', 'site', 'unclosed','initiated','graduated','male','female','age10','age14','age20','pregnant','justice','foster','runaway','lgbt']) -%>
<% @ppr_data.each do |i| -%>
<%= CSV.generate_line([i[:n_provider].gsub("'","").gsub("&","and"), i[:n_site].gsub("'","").gsub("&","and"), i[:n_unclosed], i[:n_initiated], i[:n_graduated], i[:n_male], i[:n_female], i[:n_10], i[:n_14], i[:n_20], i[:n_preg], i[:n_justice], i[:n_foster], i[:n_runaway], i[:n_lgbt]]) -%>
<% end -%>